backend:
  name: github
  repo: arturogh/arturogoicochea.com

publish_mode: editorial_workflow

media_folder: static/assets/images
public_folder: assets/images

collections:
  - name: 'posts'
    label: 'Posts'
    folder: 'src/pages/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {name: 'path', label: 'Path', widget: 'string'}
      - {name: 'date', label: 'Date', widget: 'date'}
      - {name: title, label: Title, widget: 'string'}
      - {name: excerpt, label: Excerpt, widget: 'string'}
      - {name: body, label: Body, widget: markdown}
      - {label: 'Tags', name: 'tags', widget: 'list'}
  - name: 'projects'
    label: 'Projects'
    folder: 'src/pages/projects'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {name: 'path', label: 'Path', widget: 'string'}
      - {name: 'date', label: 'Date', widget: 'date'}
      - {name: title, label: Title, widget: 'string'}
      - {name: excerpt, label: Excerpt, widget: 'string'}
      - {name: body, label: Body, widget: markdown}
      - {label: 'Tags', name: 'tags', widget: 'list'}
