backend:
  name: github
  repo: arturogh/arturogoicochea.com

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    fields:
      - {name: path, label: Path}
      - {name: date, label: Date, widget: date}
      - {name: title, label: Title}
      - {name: excerpt, label: Excerpt, widget: markdown}
      - {name: body, label: Body, widget: markdown}
